
stages:
  - build
  - deploy

build frontend:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - frontend-runner
  script:
    - docker build -t front:latest .
    - docker-compose up -d

deploy frontend:
  stage: deploy
  only:
    refs:
      - 46-dokerize-front-end
      - main # only branch to be deploye
  tags:
    - frontend-runner
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - docker cp front:/usr/local/app/dist/. ~/front-deployment/
