version: '3.3'
services:

  front:
    container_name: "front"
    image: front:latest
    ports:
     - "80:80"
     - "443:443"
    networks:
      - mynet
    volumes:
      - ./cert/www:/var/www/certbot/:ro
      - ./cert/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  API:
    image: bootdocker:staging
    container_name: "back"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=local
      - AWS_REGION=local
      - ENVIRONMENT=local
    networks:
      - mynet
    restart: always

  db:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_ROOT_PASSWORD=postgres

    user: postgres
    ports:
      - "5632:5432"
    healthcheck:
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - mynet
networks:
  mynet:
    driver: bridge


