version: '3.3'
services:

  front:
    container_name: "front"
    image: front:latest
    ports:
     - "80:80"
    restart: always
    networks:
      mynet:
        ipv4_address: 10.5.0.5

  API:
    image: bootdocker:staging
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=local
      - AWS_REGION=local
      - ENVIRONMENT=local
    networks:
      mynet:
          ipv4_address: 10.5.0.6
  db:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_ROOT_PASSWORD=postgres

    user: postgres
    ports:
      - "5632:5432"
    healthcheck:
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

